import { NextRequest, NextResponse } from "next/server";
import { ingestUserToken, metaConnectionStatus } from "@/lib/metaHeal";

// Owner-only Meta (Facebook/Instagram) reconnect. Auth-gated via the /api/settings
// matcher in proxy.ts. The owner pastes a fresh Facebook USER token (generated by
// THEM in Meta's Graph API Explorer — only they can log into Facebook); the server
// exchanges it for a long-lived token, mints the Page publishing token, stores it,
// and self-refreshes from then on (lib/metaHeal). The token never passes through chat.
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// GET -> current publishing-connection status (read-only).
export async function GET() {
  try {
    return NextResponse.json(await metaConnectionStatus());
  } catch (e) {
    return NextResponse.json({ status: "error", detail: e instanceof Error ? e.message : "error" });
  }
}

// POST { userToken } -> mint + store the Page token; turns auto-publishing ON.
export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => ({}));
  const userToken = String(body.userToken || "").trim();
  if (!userToken) {
    return NextResponse.json({ status: "error", detail: "Paste your Facebook user token to connect." }, { status: 400 });
  }
  const result = await ingestUserToken(userToken);
  return NextResponse.json(result, { status: result.status === "healed" ? 200 : 400 });
}
