// NANP area code → geographic home ("City area, ST"). Caller-ID context only:
// tells Ramon where a number is FROM before anything else loads. State is always
// right; the city names the code's principal metro. Codes we don't know return
// null and the UI simply omits the location line (overlays/new codes fail soft).
const AC: Record<string, string> = {
  // --- California ---
  "209": "Stockton/Modesto, CA", "213": "Los Angeles (Downtown), CA", "279": "Sacramento, CA",
  "310": "Los Angeles (Westside/South Bay), CA", "323": "Los Angeles, CA", "341": "Oakland/East Bay, CA",
  "350": "Stockton/Modesto, CA", "369": "North Bay, CA", "408": "San Jose, CA", "415": "San Francisco, CA",
  "424": "Los Angeles (Westside/South Bay), CA", "442": "Palm Springs/Oceanside, CA", "510": "Oakland/East Bay, CA",
  "530": "Redding/Chico, CA", "559": "Fresno, CA", "562": "Long Beach, CA", "619": "San Diego, CA",
  "626": "Pasadena/San Gabriel Valley, CA", "628": "San Francisco, CA", "650": "Peninsula/Palo Alto, CA",
  "657": "Anaheim/Orange County, CA", "661": "Bakersfield/Palmdale, CA", "669": "San Jose, CA",
  "707": "Santa Rosa/Napa, CA", "714": "Anaheim/Orange County, CA", "747": "San Fernando Valley, CA",
  "760": "Palm Springs/Oceanside, CA", "805": "Ventura/Santa Barbara, CA", "818": "San Fernando Valley, CA",
  "820": "Ventura/Santa Barbara, CA", "831": "Monterey/Santa Cruz, CA", "840": "San Bernardino, CA",
  "858": "San Diego (North), CA", "909": "San Bernardino/Riverside, CA", "916": "Sacramento, CA",
  "925": "Concord/Walnut Creek, CA", "949": "Irvine/South Orange County, CA", "951": "Riverside, CA",
  // --- Florida ---
  "239": "Fort Myers/Naples, FL", "305": "Miami, FL", "321": "Orlando/Space Coast, FL",
  "352": "Gainesville/Ocala, FL", "386": "Daytona Beach, FL", "407": "Orlando, FL",
  "561": "West Palm Beach, FL", "645": "Miami, FL", "656": "Orlando, FL", "689": "Orlando, FL",
  "727": "St. Petersburg/Clearwater, FL", "728": "West Palm Beach, FL", "754": "Fort Lauderdale, FL",
  "772": "Port St. Lucie/Treasure Coast, FL", "786": "Miami, FL", "813": "Tampa, FL",
  "850": "Tallahassee/Panhandle, FL", "863": "Lakeland, FL", "904": "Jacksonville, FL",
  "941": "Sarasota/Bradenton, FL", "954": "Fort Lauderdale, FL",
  // --- Michigan ---
  "231": "Muskegon/Traverse City, MI", "248": "Oakland County/Troy, MI", "269": "Kalamazoo, MI",
  "313": "Detroit, MI", "517": "Lansing, MI", "586": "Macomb County/Warren, MI",
  "616": "Grand Rapids, MI", "679": "Detroit, MI", "734": "Ann Arbor, MI", "810": "Flint, MI",
  "906": "Upper Peninsula, MI", "947": "Oakland County, MI", "989": "Saginaw, MI",
  // --- Northeast ---
  "201": "Jersey City/Hackensack, NJ", "551": "Jersey City/Hackensack, NJ", "202": "Washington, DC",
  "203": "Bridgeport/New Haven, CT", "475": "Bridgeport/New Haven, CT", "860": "Hartford, CT", "959": "Hartford, CT",
  "207": "Maine, ME", "212": "New York City (Manhattan), NY", "332": "New York City (Manhattan), NY",
  "646": "New York City (Manhattan), NY", "215": "Philadelphia, PA", "267": "Philadelphia, PA", "445": "Philadelphia, PA",
  "216": "Cleveland, OH", "217": "Springfield, IL", "447": "Springfield, IL", "218": "Duluth, MN",
  "223": "Harrisburg/Lancaster, PA", "717": "Harrisburg/Lancaster, PA", "570": "Scranton/Wilkes-Barre, PA", "272": "Scranton, PA",
  "412": "Pittsburgh, PA", "878": "Pittsburgh, PA", "610": "Allentown/Reading, PA", "484": "Allentown/Reading, PA",
  "724": "Western PA, PA", "814": "Erie/Altoona, PA", "582": "Erie/Altoona, PA",
  "301": "Southern MD/DC suburbs, MD", "240": "Southern MD/DC suburbs, MD", "410": "Baltimore, MD",
  "443": "Baltimore, MD", "667": "Baltimore, MD", "227": "Southern MD, MD",
  "302": "Delaware, DE", "304": "West Virginia, WV", "681": "West Virginia, WV",
  "315": "Syracuse, NY", "680": "Syracuse, NY", "316": "Wichita, KS", "516": "Nassau County/Long Island, NY",
  "518": "Albany, NY", "838": "Albany, NY", "585": "Rochester, NY", "607": "Binghamton/Ithaca, NY",
  "631": "Suffolk County/Long Island, NY", "934": "Suffolk County/Long Island, NY",
  "716": "Buffalo, NY", "718": "New York City (Brooklyn/Queens/Bronx), NY", "347": "New York City (outer boroughs), NY",
  "929": "New York City (outer boroughs), NY", "917": "New York City, NY", "845": "Hudson Valley, NY",
  "914": "Westchester County, NY", "919": "Raleigh/Durham, NC", "984": "Raleigh/Durham, NC",
  "401": "Rhode Island, RI", "413": "Springfield, MA", "508": "Worcester/Cape Cod, MA", "774": "Worcester/Cape Cod, MA",
  "617": "Boston, MA", "857": "Boston, MA", "781": "Boston suburbs, MA", "339": "Boston suburbs, MA",
  "978": "Lowell/North Shore, MA", "351": "Lowell/North Shore, MA",
  "603": "New Hampshire, NH", "802": "Vermont, VT",
  "609": "Trenton/South Jersey shore, NJ", "640": "Trenton/South Jersey, NJ", "732": "Central Jersey, NJ",
  "848": "Central Jersey, NJ", "856": "Camden/South Jersey, NJ", "862": "Newark, NJ", "973": "Newark, NJ",
  "908": "Elizabeth/Union County, NJ",
  // --- South ---
  "205": "Birmingham, AL", "251": "Mobile, AL", "256": "Huntsville, AL", "334": "Montgomery, AL", "659": "Birmingham, AL",
  "228": "Gulfport/Biloxi, MS", "601": "Jackson, MS", "662": "Northern MS, MS", "769": "Jackson, MS",
  "229": "Albany, GA", "404": "Atlanta, GA", "470": "Atlanta, GA", "678": "Atlanta, GA", "770": "Atlanta suburbs, GA",
  "706": "Augusta/Columbus, GA", "762": "Augusta/Columbus, GA", "912": "Savannah, GA", "943": "Atlanta, GA",
  "252": "Eastern NC, NC", "704": "Charlotte, NC", "980": "Charlotte, NC", "336": "Greensboro/Winston-Salem, NC",
  "743": "Greensboro, NC", "828": "Asheville, NC", "910": "Fayetteville/Wilmington, NC",
  "803": "Columbia, SC", "839": "Columbia, SC", "843": "Charleston, SC", "854": "Charleston, SC", "864": "Greenville, SC",
  "276": "Southwest VA, VA", "434": "Charlottesville/Lynchburg, VA", "540": "Roanoke/Shenandoah, VA",
  "571": "Northern Virginia, VA", "703": "Northern Virginia, VA", "757": "Norfolk/Virginia Beach, VA", "948": "Norfolk/Virginia Beach, VA",
  "804": "Richmond, VA", "826": "Richmond, VA",
  "270": "Bowling Green/Western KY, KY", "364": "Western KY, KY", "502": "Louisville, KY", "606": "Eastern KY, KY", "859": "Lexington, KY",
  "423": "Chattanooga/Tri-Cities, TN", "615": "Nashville, TN", "629": "Nashville, TN", "731": "Jackson, TN",
  "865": "Knoxville, TN", "901": "Memphis, TN", "931": "Clarksville, TN",
  "225": "Baton Rouge, LA", "318": "Shreveport, LA", "337": "Lafayette, LA", "504": "New Orleans, LA", "985": "Houma/North Shore, LA",
  "479": "Fort Smith/Fayetteville, AR", "501": "Little Rock, AR", "870": "Jonesboro/Pine Bluff, AR",
  "405": "Oklahoma City, OK", "572": "Oklahoma City, OK", "539": "Tulsa, OK", "918": "Tulsa, OK", "580": "Lawton, OK",
  // --- Texas ---
  "210": "San Antonio, TX", "726": "San Antonio, TX", "214": "Dallas, TX", "469": "Dallas, TX", "972": "Dallas, TX",
  "945": "Dallas, TX", "254": "Waco/Killeen, TX", "281": "Houston, TX", "713": "Houston, TX", "832": "Houston, TX",
  "346": "Houston, TX", "621": "Houston, TX", "325": "Abilene, TX", "361": "Corpus Christi, TX",
  "409": "Beaumont/Galveston, TX", "430": "Tyler/East TX, TX", "903": "Tyler/East TX, TX",
  "432": "Midland/Odessa, TX", "512": "Austin, TX", "737": "Austin, TX", "806": "Amarillo/Lubbock, TX",
  "817": "Fort Worth, TX", "682": "Fort Worth, TX", "830": "Hill Country, TX", "915": "El Paso, TX",
  "936": "Huntsville/Conroe, TX", "940": "Wichita Falls/Denton, TX", "956": "Laredo/Rio Grande Valley, TX",
  // --- Midwest ---
  "219": "Gary/Northwest IN, IN", "260": "Fort Wayne, IN", "317": "Indianapolis, IN", "463": "Indianapolis, IN",
  "574": "South Bend, IN", "765": "Muncie/Lafayette, IN", "812": "Evansville/Bloomington, IN", "930": "Southern IN, IN",
  "220": "Southeastern OH, OH", "234": "Akron/Canton, OH", "330": "Akron/Canton, OH", "283": "Cincinnati, OH",
  "513": "Cincinnati, OH", "326": "Dayton, OH", "937": "Dayton, OH", "380": "Columbus, OH", "614": "Columbus, OH",
  "419": "Toledo, OH", "567": "Toledo, OH", "440": "Cleveland suburbs, OH", "740": "Southeastern OH, OH",
  "224": "Chicago northwest suburbs, IL", "847": "Chicago northwest suburbs, IL", "312": "Chicago (Loop), IL",
  "872": "Chicago, IL", "773": "Chicago, IL", "331": "Chicago west suburbs, IL", "630": "Chicago west suburbs, IL",
  "618": "Southern IL, IL", "708": "Chicago south suburbs, IL", "779": "Rockford, IL", "815": "Rockford/Joliet, IL",
  "309": "Peoria, IL", "861": "Peoria, IL",
  "262": "Southeastern WI, WI", "274": "Green Bay, WI", "920": "Green Bay/Appleton, WI", "414": "Milwaukee, WI",
  "534": "Northwestern WI, WI", "715": "Northwestern WI, WI", "608": "Madison, WI", "353": "Madison, WI",
  "320": "Central MN, MN", "507": "Rochester, MN", "612": "Minneapolis, MN",
  "651": "St. Paul, MN", "763": "Minneapolis northwest suburbs, MN", "952": "Minneapolis southwest suburbs, MN",
  "308": "Western NE, NE", "402": "Omaha/Lincoln, NE", "531": "Omaha/Lincoln, NE",
  "319": "Cedar Rapids, IA", "515": "Des Moines, IA", "563": "Davenport, IA", "641": "Central IA, IA", "712": "Western IA, IA",
  "314": "St. Louis, MO", "557": "St. Louis, MO", "417": "Springfield, MO", "573": "Columbia/Jefferson City, MO",
  "636": "St. Louis suburbs, MO", "660": "Northern MO, MO", "816": "Kansas City, MO", "975": "Kansas City, MO",
  "913": "Kansas City, KS", "620": "Southern KS, KS", "785": "Topeka, KS",
  "605": "South Dakota, SD", "701": "North Dakota, ND",
  // --- West ---
  "206": "Seattle, WA", "253": "Tacoma, WA", "360": "Vancouver/Olympia, WA", "564": "Western WA, WA",
  "425": "Bellevue/Everett, WA", "509": "Spokane, WA",
  "208": "Idaho, ID", "986": "Idaho, ID", "303": "Denver, CO", "720": "Denver, CO", "983": "Denver, CO",
  "719": "Colorado Springs, CO", "970": "Fort Collins/Western CO, CO",
  "307": "Wyoming, WY", "406": "Montana, MT", "435": "Southern/Eastern UT, UT", "801": "Salt Lake City, UT", "385": "Salt Lake City, UT",
  "480": "Phoenix (East Valley/Scottsdale), AZ", "602": "Phoenix, AZ", "623": "Phoenix (West Valley), AZ",
  "520": "Tucson, AZ", "928": "Northern AZ/Yuma, AZ",
  "505": "Albuquerque, NM", "575": "Las Cruces, NM",
  "702": "Las Vegas, NV", "725": "Las Vegas, NV", "775": "Reno, NV",
  "503": "Portland, OR", "971": "Portland, OR", "541": "Eugene/Bend, OR", "458": "Eugene/Bend, OR",
  "808": "Hawaii, HI", "907": "Alaska, AK",
  // --- Territories & toll-free-ish oddities ---
  "787": "Puerto Rico, PR", "939": "Puerto Rico, PR", "340": "U.S. Virgin Islands, VI", "671": "Guam, GU", "670": "Northern Mariana Islands, MP",
  // --- Canada (common) ---
  "204": "Manitoba, Canada", "226": "London, ON, Canada", "236": "Vancouver, BC, Canada", "249": "Northern ON, Canada",
  "250": "British Columbia, Canada", "289": "Hamilton/Niagara, ON, Canada", "306": "Saskatchewan, Canada",
  "343": "Ottawa, ON, Canada", "365": "Hamilton, ON, Canada", "403": "Calgary, AB, Canada", "416": "Toronto, ON, Canada",
  "437": "Toronto, ON, Canada", "438": "Montreal, QC, Canada", "450": "Montreal suburbs, QC, Canada",
  "506": "New Brunswick, Canada", "514": "Montreal, QC, Canada", "519": "London/Windsor, ON, Canada",
  "548": "London, ON, Canada", "587": "Alberta, Canada", "604": "Vancouver, BC, Canada", "613": "Ottawa, ON, Canada",
  "639": "Saskatchewan, Canada", "647": "Toronto, ON, Canada", "705": "Northern ON, Canada", "709": "Newfoundland, Canada",
  "778": "British Columbia, Canada", "780": "Edmonton, AB, Canada", "782": "Nova Scotia, Canada",
  "807": "Thunder Bay, ON, Canada", "819": "Gatineau/Quebec, QC, Canada", "825": "Alberta, Canada",
  "867": "Northern Territories, Canada", "873": "Quebec, QC, Canada", "902": "Nova Scotia/PEI, Canada", "905": "Toronto suburbs, ON, Canada",
};

const TOLL_FREE = new Set(["800", "833", "844", "855", "866", "877", "888"]);

export function areaCodeLocation(digits10: string): string | null {
  const npa = String(digits10 || "").slice(0, 3);
  if (TOLL_FREE.has(npa)) return "Toll-free (no geography)";
  if (npa === "900") return "Premium-rate (900)";
  return AC[npa] || null;
}
