// GENERATED by scripts/dataset/exemplars.ts — do not hand-edit.
//
// Real flags this engine raised that Ramon, a licensed broker, then OVERRULED — he counted the
// income anyway. They are injected into the QC prompt so the reviewer learns which cautions are
// noise on THIS book of business, instead of raising the same objection he has already rejected
// 19 times.
//
// Regenerate deliberately (npx tsx scripts/dataset/exemplars.ts --write) and bump LOGIC_VERSION:
// this text changes QC output, and a silently drifting prompt is how income stops being
// reproducible.
//
// Redacted at generation: names -> "the borrower", SSN/email/phone stripped, and any row still
// identifying is dropped rather than shipped.
export const OVERRIDE_EXEMPLARS: { product: string; flag: string }[] = [
  {
    "product": "FHA Purchase + Down Payment Assistance",
    "flag": "Overtime/shift/holiday premium is a large share of pay but MTA tenure < 2 years (hire [DATE]) — not yet seasoned; creditable once a 2-yr history + continuance is documented"
  },
  {
    "product": "VA Purchase",
    "flag": "the borrower variable/gig income — 2-yr avg $X/mo (2023 $X + 2024 $X ÷2); most-recent 2024 $X/mo; unfiled 2025 corroborates only"
  },
  {
    "product": "VA Purchase",
    "flag": "the borrower pay frequency: monthly rate confirmed from single monthly stubs — verify no step/variable pay pulled in"
  },
  {
    "product": "VA Purchase",
    "flag": "the borrower variable/gig income (actor) — 2-yr avg $X/mo (2023 $X own W-2s+1099 $X/mo + 2024 $X $X/mo); most-recent 2024 $X/mo; unfiled 2025 W-2/1099 only corroborate trend, not cou"
  },
  {
    "product": "VA Purchase",
    "flag": "the borrower variable/gig income — 2-yr avg $X/mo; 2024 documented (W-2 $X + 1099 $X = $X) = $X/mo. 2023 individual W-2s not on file; only joint return. [REDACTED] at most-recent documente"
  },
  {
    "product": "VA Purchase",
    "flag": "the borrower 2025 W-2/1099 ([REDACTED] $X, [REDACTED] $X) are unfiled current-year — corroborate only, not counted"
  },
  {
    "product": "DSCR Purchase",
    "flag": "[REDACTED] variable/multi-employer income — 2-yr avg $X/mo (2024 $X + 2025 stub-YTD $X); most-recent 2026 stub trending higher"
  },
  {
    "product": "DSCR Purchase",
    "flag": "[REDACTED] stubs dated 2026 — verify current continuous employment / most-recent full-year 1099/W-2"
  },
  {
    "product": "VA Purchase",
    "flag": "the borrower 2023 needs individual W-2/[REDACTED]&[REDACTED] transcript to firm the 2-yr average"
  },
  {
    "product": "FHA Purchase + Down Payment Assistance",
    "flag": "Rising hourly rate across recent stubs ($X → $X → $X) — verify current base rate and hours with a VOE"
  },
  {
    "product": "FHA Purchase + Down Payment Assistance",
    "flag": "[REDACTED] of [REDACTED]: prior/former employer — no current pay stub on file, so counted as work history (a job change), not current income. Omit to count it as concurrent income."
  },
  {
    "product": "FHA Purchase + Down Payment Assistance",
    "flag": "QC: Reasonableness: sole 2026 bank deposit shows [REDACTED] payroll of $X net the borrower one biweekly period (~$X/mo gross-equivalent), consistent with ~$X gross/mo. [REDACTED] $X qualifying figure i"
  },
  {
    "product": "FHA Purchase + Down Payment Assistance",
    "flag": "QC: Base salary should be computed from current stub regular rate ($X biweekly ×26÷12 ≈ $X) — but total qualifying income of $X is [REDACTED] than base alone, suggesting the engine under-cou"
  },
  {
    "product": "FHA Purchase + Down Payment Assistance",
    "flag": "QC: [REDACTED] base computed as $X biweekly ×26÷12 = $X/mo alone, which already exceeds the $X total; the worksheet basis '×26÷12 + variable 2-yr avg' does not arithmetically reconcile to $X"
  },
  {
    "product": "FHA Purchase + Down Payment Assistance",
    "flag": "QC: OT/holiday/shift premium is substantial and recurring across both 2026 stubs (YTD gross $X vs YTD regular $X through 06/20) but the worksheet lumps only a vague 'variable 2-yr avg'; OT s"
  },
  {
    "product": "VA Purchase",
    "flag": "[REDACTED]borrower [REDACTED]: variable pay declining [REDACTED] — using the lower current year. Omit to use the 2-yr average."
  },
  {
    "product": "VA Purchase",
    "flag": "QC ⚠️: [REDACTED] $X base is contradicted by the borrower's own YTD: [DATE] stub shows YTD gross $X through 6 months ≈ $X/mo, not $X×12=$X/yr. [REDACTED] $X period appears to be a p"
  },
  {
    "product": "VA Purchase",
    "flag": "[REDACTED]borrower [REDACTED]: prior/former employer — no current pay stub on file, so counted as work history (a job change), not current income. Omit to count it as concurrent income."
  },
  {
    "product": "VA Purchase",
    "flag": "QC: the borrower's documented streams (2024 MFJ 1040 shows W-2 wages included in $X total, 2025 [REDACTED]2 Box1 $X 1099-[REDACTED] $X from [REDACTED], ongoing VA benefit $X/mo recu"
  }
];

/** The block appended to VERIFY_SYSTEM. Empty string when there are no exemplars. */
export function overrideGuidance(): string {
  if (!OVERRIDE_EXEMPLARS.length) return "";
  const lines = OVERRIDE_EXEMPLARS.map((o) => `  - [${o.product}] ${o.flag}`).join("\n");
  return `

FLAGS THIS LENDER HAS ALREADY REJECTED. The following are real flags this engine raised and the
licensed broker then OVERRULED, counting the income anyway. They are not rules, and they do not
license you to skip a check — but if your finding is materially the same objection as one below,
it has been judged noise on this book of business before. Raise it only if THIS file gives you a
specific reason the earlier judgement does not apply, and say what that reason is.

${lines}`;
}
