#!/usr/bin/env node
// GENERATE voice-realtime/mortgageKB.js FROM lib/voice/mortgageKB.ts — ONE SOURCE OF TRUTH.
//
// 2026-10-06, Ramon: "Let's upgrade Penny's answering service capabilities... people are still not
// understanding every conversation that people are calling to have with you. And you're supposed to
// be just as good as a live person."
//
// The cause was not her manner — her message-taking instructions are excellent. The cause is that
// `lib/voice/mortgageKB.ts` — 33 sections, 30 FAQs, CORE_PRODUCTS and CORE_LAW, built from Ramon's
// licensed Mortgage Educators textbook and compliance-verified — is referenced **ZERO times** by the
// realtime bridge. Someone built Penny a brain and never connected it. Her instructions contained no
// mention of FHA, VA, DSCR, credit scores, or which states Fetti is licensed in, so a caller asking
// "do you do FHA with a 580?" got a message taken instead of an answer.
//
// The bridge is ESM plain JS on Render; the KB is TypeScript in the Next app. Rather than hand-copy
// (which guarantees drift the first time the KB is regenerated), this strips the type annotations
// mechanically and writes a JS module. Re-run it whenever the KB changes:
//
//   node voice-realtime/build-kb.mjs        # regenerate
//   node voice-realtime/build-kb.mjs --check  # fail if the generated file is stale
//
// Exit 1 = source unreadable, or --check found the generated copy out of date.
import fs from "fs";
import path from "path";
import crypto from "crypto";
import { fileURLToPath } from "url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(HERE, "..", "lib", "voice", "mortgageKB.ts");
const OUT = path.join(HERE, "mortgageKB.js");

function strip(ts) {
  let s = ts;
  // The KB is data plus two small pure functions. Only these shapes carry TS syntax.
  // The type line contains semicolons INSIDE its braces (`id: string; title: string;`), so a
  // `[^;]+` pattern stops at the first one and leaves `export type` in the output — which then
  // dies at import with "Unexpected token 'export'". Match the whole line instead.
  s = s.replace(/^export type KBSection = .*$/m, "");
  s = s.replace(/export const (\w+): string =/g, "export const $1 =");
  s = s.replace(/export const KB_SECTIONS: KBSection\[\] =/g, "export const KB_SECTIONS =");
  s = s.replace(/export const KB_FAQS: \{[^}]*\}\[\] =/g, "export const KB_FAQS =");
  s = s.replace(/export function retrieveKB\(query: string, n = 3\): KBSection\[\]/g,
                "export function retrieveKB(query, n = 3)");
  s = s.replace(/export function kbContextFor\(query: string, n = 3\): string/g,
                "export function kbContextFor(query, n = 3)");
  s = s.replace(/\.map\(\(s\) =>/g, ".map((s) =>");
  return s;
}

const banner = (hash) =>
  `// GENERATED by voice-realtime/build-kb.mjs from lib/voice/mortgageKB.ts — DO NOT HAND-EDIT.\n` +
  `// Edit the TypeScript source and re-run the generator, or the two will drift apart silently.\n` +
  `// source sha256: ${hash}\n\n`;

if (!fs.existsSync(SRC)) {
  console.error(`[build-kb] UNREADABLE — no source at ${SRC}`);
  process.exit(1);
}
const ts = fs.readFileSync(SRC, "utf8");
const hash = crypto.createHash("sha256").update(ts).digest("hex");
const js = banner(hash) + strip(ts);

if (process.argv.includes("--check")) {
  if (!fs.existsSync(OUT)) { console.error("[build-kb] STALE — generated file missing. Run the generator."); process.exit(1); }
  const cur = fs.readFileSync(OUT, "utf8");
  const m = cur.match(/source sha256: ([0-9a-f]{64})/);
  if (!m || m[1] !== hash) {
    console.error(`[build-kb] STALE — mortgageKB.js was generated from a DIFFERENT source.`);
    console.error(`           Penny would be answering from an out-of-date knowledge base.`);
    console.error(`           expected ${hash.slice(0, 16)}…  found ${(m ? m[1] : "none").slice(0, 16)}…`);
    process.exit(1);
  }
  console.log(`[build-kb] current — generated copy matches the source (${hash.slice(0, 16)}…)`);
  process.exit(0);
}

// REFUSE TO WRITE A FILE THAT WILL NOT IMPORT. The first cut emitted a surviving `export type`
// line and the module died at import — which on a live call means Penny answers with no knowledge
// at all and nothing tells you why. Check before writing, not after.
const leftovers = js.match(/^export type .*$|^\s*(interface|declare) /m);
if (leftovers) {
  console.error(`[build-kb] REFUSING TO WRITE — TypeScript syntax survived the strip:`);
  console.error(`           ${leftovers[0].slice(0, 90)}`);
  console.error(`           That file would throw at import and Penny would run with no knowledge base.`);
  process.exit(1);
}
fs.writeFileSync(OUT, js);
console.log(`[build-kb] wrote ${OUT} (${js.length} bytes) from source ${hash.slice(0, 16)}…`);
